# -*- coding: utf-8 -*-
"""Password Generator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yaJm4pA0NtZXROgVmAZLi39pfg7hYYQn
"""

import random
import string

def generate_password(length):
    """Generate a random password."""
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def get_valid_length():
    """Prompt the user to enter a valid password length."""
    while True:
        try:
            length = int(input("Enter the desired length for your password: "))
            if length < 4:
                print("Password length must be at least 4 characters.")
            else:
                return length
        except ValueError:
            print("Please enter a valid integer.")

# Main function
def main():
    print("Welcome to the Random Password Generator!")

    # Get password length from the user
    length = get_valid_length()

    # Generate password
    password = generate_password(length)

    # Display the generated password
    print("Generated Password:", password)

# Run the main function
if __name__ == "__main__":
    main()